---
apiVersion: v1
kind: Service
metadata:
  name: go-magazines-default
spec:
  selector:
    app: go-magazines-default
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-magazines-default
spec:
  selector:
    matchLabels:
      app: go-magazines-default
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-magazines-default
    spec:
      containers:
      - name: go-magazines-default
        image: ayax79/go-magazines
        imagePullPolicy: Always
        resources:
          requests:
            memory: 0.1G
            cpu: "0.1"
          limits:
            memory: 0.5G
            cpu: "0.5"
        ports:
          - name: http-api
            containerPort: 8080
        env:
          - name: BOOKSTORE_REDISPASSWORD
            valueFrom:
              secretKeyRef:
                name: REDIS_NAME
                key: redis-password
          - name: BOOKSTORE_REDISHOST
            value: REDIS_HOST
          - name: BOOKSTORE_REDISPORT
            value: "6379"